namespace Sirenix.Serialization
{
	public enum BinaryEntryType : byte
	{
		Invalid = 0,
		NamedStartOfReferenceNode = 1,
		UnnamedStartOfReferenceNode = 2,
		NamedStartOfStructNode = 3,
		UnnamedStartOfStructNode = 4,
		EndOfNode = 5,
		StartOfArray = 6,
		EndOfArray = 7,
		PrimitiveArray = 8,
		NamedInternalReference = 9,
		UnnamedInternalReference = 10,
		NamedExternalReferenceByIndex = 11,
		UnnamedExternalReferenceByIndex = 12,
		NamedExternalReferenceByGuid = 13,
		UnnamedExternalReferenceByGuid = 14,
		NamedSByte = 15,
		UnnamedSByte = 16,
		NamedByte = 17,
		UnnamedByte = 18,
		NamedShort = 19,
		UnnamedShort = 20,
		NamedUShort = 21,
		UnnamedUShort = 22,
		NamedInt = 23,
		UnnamedInt = 24,
		NamedUInt = 25,
		UnnamedUInt = 26,
		NamedLong = 27,
		UnnamedLong = 28,
		NamedULong = 29,
		UnnamedULong = 30,
		NamedFloat = 31,
		UnnamedFloat = 32,
		NamedDouble = 33,
		UnnamedDouble = 34,
		NamedDecimal = 35,
		UnnamedDecimal = 36,
		NamedChar = 37,
		UnnamedChar = 38,
		NamedString = 39,
		UnnamedString = 40,
		NamedGuid = 41,
		UnnamedGuid = 42,
		NamedBoolean = 43,
		UnnamedBoolean = 44,
		NamedNull = 45,
		UnnamedNull = 46,
		TypeName = 47,
		TypeID = 48,
		EndOfStream = 49,
		NamedExternalReferenceByString = 50,
		UnnamedExternalReferenceByString = 51
	}
}
